[package]
name = "web3_openethereum_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web3 = "0.16.0"
tokio = { version = "1.2", features = ["full"] }